// Generated by CoffeeScript 1.4.0

$(function() {
  $(window).resize(function() {
    $(".task .wrapper-list").css("min-height", $(window).height() - 203);
    return $("#group .wrapper-overflow, #group .wrapper-list").height($(window).height() - 203);
  });
  return $(window).resize();
});
